server:
  port: 8080
#TODO use eureka to discover the URL for the service1 and service2
#TODO configure spring cloud gateway to route the request to downstream services (service1 and service2) based on the paths(/api/greeting, /product)
#TODO for greeting endpoint add a route to accept requests to /greeting but before calling service1 it must append api before the greeting path (HINT: rewrite path filter)
#and method types (GET,POST)
spring:
  application:
    name: api-gateway # Service registers under this name
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: service1Module
          uri: http://localhost:8081/
          predicates:
            - Path=/greeting/**
          filters:
            - RewritePath=/greeting/(?<segment>.*),/api/greeting/$\{segment}
        - id: service2Module
          uri: http://localhost:8082/
          predicates:
            - Path=/product/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
    registerWithEureka: true
    fetchRegistry: true